AWSTemplateFormatVersion: 2010-09-09
Description: 'Example microservice deploy'

Parameters:
  ProjectName:
    Type: String
    Description: 'Usually pn can be pnXYZ where XYZ are the feature number, useful to create
      experimental environments without crash official development environment'

  ApiDnsName:
    Type: String
    Description: 'The DNS name used for B2B rest API.'

  CorsAllowedDomains:
    Type: String
    Description: 'Comma separated list of domains allowed to make cross origin request'

  ContainerImageUri:
    Type: String
    Description: 'Exact container image URI with full repository and image digest'

  MicroserviceNumber:
    Type: Number
    Description: 'Disambiguation useful for load balancer rules'

  TemplateBucketBaseUrl:
    Type: String
    Description: 'The S3 bucket from which to fetch the templates used by this stack.'

  SandboxSafeStorageBaseUrl:
     Type: String
     Description: 'Url to the SafeStorage microservice'

  ECSClusterName:
    Type: String
    Description: 'The name of the ECS cluster where the microservice is going to be deployed'

  SubnetsIds:
    Type: String
    Description: 'subnets ids comma separated list. Where to deploy the microservice'

  VpcEgressSubnetsIds:
    Type: String
    Description: subnets where to install PN-CORE

  VpcId:
    Type: String
    Description: 'VpcId where the microservice is going to be deployed'

  EcsDefaultSecurityGroup:
    Type: String
    Description: 'Default security group required by infrastructure'

  ApplicationLoadBalancerListenerArn:
    Type: String
    Description: 'Load balancer listener where HTTP endpoints is going to be registered'

  ApplicationLoadBalancerDomain:
    Type: String
    Description: 'Base URL of the load balancer where the service is going to be reachable'

  NetworkLoadBalancerLink:
    Type: String
    Description: 'network load balancer link for API-GW'

  AlarmSNSTopicArn:
    Type: String
    Description: ARN of alarm topic

  Version:
    Type: String
    Description: 'keep track of used projects commitIds'

  IsLollipopActive:
    Type: String
    Description: 'lollipop authorization activation flag'
    AllowedValues: [true, false]
    Default: "false"

  LollipopExpectedLcOriginalUrl:
    Type: String
    Description: 'expected lollipop consumer original url'

  LollipopEnableConsumerLogging:
    Type: String
    Description: 'enable lollipop consumer logging'

  LogsKinesisSourceStreamArn:
    Type: String
    Description: 'Kinesis stream that receive logs'

  LogsBucketName:
    Type: String
    Description: 'Logs bucket name'

  LogsKinesisFilterPattern:
    Type: String
    Default: ""
    Description: 'Log kinesis filter pattern'

  AlbSecurityGroup:
    Type: String
    Description: 'Application load balancer security group'

  # Log group parameters
  EcsLogGroup:
    Type: String
    Description: 'Ecs log group name'

  # OpenApi Bucket params
  MicroserviceBucketName:
    Type: String
    Default: ''
    Description: 'Name of the bucket where the microservice files are copied during deploy'

  MicroserviceBucketBaseKey:
    Type: String
    Default: ''
    Description: 'Base key of the microservice in the s3 bucket'

  # Heath Check parameters
  HealthCheckInterval:
    Description: Seconds between two health check
    Type: Number
    Default: 60

  HealthCheckTimeout:
    Description: health check timeout seconds
    Type: Number
    Default: 5

  HealthyThresholdCount:
    Description: |
      The number of consecutive health checks successes required before considering 
      an unhealthy target healthy.
    Type: Number
    Default: 5

  UnhealthyThresholdCount:
    Description: |
      The number of consecutive health check failures required before considering a target unhealthy.
    Type: Number
    Default: 2

  # Instance parameters
  # 256 (.25 vCPU) - Available memory values: 0.5GB, 1GB, 2GB
  # 512 (.5 vCPU) - Available memory values: 1GB, 2GB, 3GB, 4GB
  # 1024 (1 vCPU) - Available memory values: 2GB, 3GB, 4GB, 5GB, 6GB, 7GB, 8GB
  # 2048 (2 vCPU) - Available memory values: Between 4GB and 16GB in 1GB increments
  # 4096 (4 vCPU) - Available memory values: Between 8GB and 30GB in 1GB increments
  CpuValue:
    Type: Number
    Default: 1024
    Description: Fargate virtual CPU quantity 1024 equals one vCPU

  # 0.5GB, 1GB, 2GB - Available cpu values: 256 (.25 vCPU)
  # 1GB, 2GB, 3GB, 4GB - Available cpu values: 512 (.5 vCPU)
  # 2GB, 3GB, 4GB, 5GB, 6GB, 7GB, 8GB - Available cpu values: 1024 (1 vCPU)
  # Between 4GB and 16GB in 1GB increments - Available cpu values: 2048 (2 vCPU)
  # Between 8GB and 30GB in 1GB increments - Available cpu values: 4096 (4 vCPU)
  MemoryAmount:
    Type: String
    Default: 2GB
    Description: memory amount reserved to the task pod.
    AllowedValues: [ 2GB, 4GB, 6GB, 8GB ]

  # Autoscaling parameters
  AutoscalingCheckPeriod:
    Default: 60
    Type: Number
    Description: minimum autoscaling number of tasks\

  AutoscalingDataPointN:
    Default: 1
    Type: Number
    Description: activate when N datapoint on M

  AutoscalingDataPointM:
    Default: 1
    Type: Number
    Description: activate when N datapoint on M

  AutoscalingThreshold:
    Default: 70
    Type: String

  MinTasksNumber:
    Default: 1
    Type: Number
    Description: minimum autoscaling number of tasks

  MaxTasksNumber:
    Default: 6
    Type: Number
    Description: maximum autoscaling number of tasks

  LogAlarmStrategy:
    Type: String
    Default: 'FATAL'

  F24MetadataSetTableName:
    Type: String
    Description: 'Name of dynamodb table for f24 metadata set'

  F24MetadataSetTableArn:
    Type: String
    Description: 'ARN of dynamodb table for f24 metadata set'

  F24FileTableName:
    Type: String
    Description: 'Name of dynamodb table for f24 files'

  F24FileTableArn:
    Type: String
    Description: 'ARN of dynamodb table for f24 files'

  PnF24InternalQueueName:
    Type: String
    Description: 'Internal Queue name'

  PnF24InternalQueueARN:
    Type: String
    Description: 'Internal Queue ARN'

  SafeStorageToF24QueueName:
    Type: String
    Description: 'SafeStorage-to-f24 queue Name'

  SafeStorageToF24QueueARN:
    Type: String
    Description: 'SafeStorage-to-f24 queue ARN'

  SafeStorageToF24QueueAlarmARN:
    Type: String
    Description: SafeStorage-to-f24 queue alarm ARN

  SafeStorageToF24QueueAgeAlarmARN:
    Type: String
    Description: SafeStorage-to-f24 queue age alarm ARN

  F24EventBusName:
    Type: String
    Description: F24 event bus name

  F24EventBusARN:
    Type: String
    Description: F24 event bus ARN

  F24EventBusDLQARN:
    Type: String
    Description: F24 event bus DLQ ARN

  PnCoreTargetEventBus:
    Type: String
    Description: ARN of the core target event bus

Conditions:
    SendLogToKinesis: !Not [ !Equals [ !Ref LogsKinesisSourceStreamArn, '' ] ]

Resources:

  # PN-F24 microservice
  F24Microservice:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub "${TemplateBucketBaseUrl}/fragments/ecs-service.yaml"
      Parameters:
        MicroServiceUniqueName: !Sub '${ProjectName}-f24'
        CpuValue: !Ref CpuValue
        MemoryAmount: !Ref MemoryAmount
        HealthCheckPath: /actuator/health
        HealthCheckTimeout: !Ref HealthCheckTimeout
        HealthCheckInterval: !Ref HealthCheckInterval
        HealthyThresholdCount: !Ref HealthyThresholdCount
        UnhealthyThresholdCount: !Ref UnhealthyThresholdCount
        AutoscalingStrategy: REST-API
        AutoscalingThreshold: !Ref AutoscalingThreshold
        AutoscalingCheckPeriod: !Ref AutoscalingCheckPeriod
        MinTasksNumber: !Ref MinTasksNumber
        MaxTasksNumber: !Ref MaxTasksNumber
        AutoscalingDataPointN: !Ref AutoscalingDataPointN
        AutoscalingDataPointM: !Ref AutoscalingDataPointM
        AlarmSNSTopicArn: !Ref AlarmSNSTopicArn
        ContainerImageURI: !Sub '${ContainerImageUri}'
        ContainerEnvEntry1: !Sub 'AWS_REGIONCODE=${AWS::Region}'
        ContainerEnvEntry2: !Sub 'CORS_ALLOWED_DOMAINS=${CorsAllowedDomains}'
        ContainerEnvEntry3: !Sub 'PN_DELIVERY_PUSH_BASE_URL=http://${ApplicationLoadBalancerDomain}:8080'
        ContainerEnvEntry4: !Sub 'PN_F24_METADATA_SET_TABLE_NAME=${F24MetadataSetTableName}'
        ContainerEnvEntry5: !Sub 'PN_F24_FILE_TABLE_NAME=${F24FileTableName}'
        ContainerEnvEntry6: !Sub 'SPRING_CLOUD_FUNCTIONROUTER_QUEUES_LIST=${PnF24InternalQueueName},${SafeStorageToF24QueueName}'
        ContainerEnvEntry7: !Sub 'LOLLIPOP_ACTIVE=${IsLollipopActive}'
        ContainerEnvEntry8: !Sub 'PN_SAFESTORAGE_BASE_URL=${SandboxSafeStorageBaseUrl}'
        ContainerEnvEntry9: !Sub 'PN_F24_TOPICS_INTERNAL=${PnF24InternalQueueName}'
        ContainerEnvEntry10: !Sub 'PN_F24_TOPICS_FROM_SAFE_STORAGE=${SafeStorageToF24QueueName}'
        ContainerEnvEntry11: !Sub 'PN_F24_EVENTBUS_NAME=${F24EventBusName}'
        ContainerEnvEntry18: !Sub 'LOLLIPOP_EXPECTED_LC_ORIGINAL_URL=${LollipopExpectedLcOriginalUrl}'
        ContainerEnvEntry19: !Sub 'LOLLIPOP_ENABLE_CONSUMER_LOGGING=${LollipopEnableConsumerLogging}'
        MicroServiceSecretPrefix: pn-f24-Secrets
        JavaToolOptions: '-Dreactor.netty.ioWorkerCount=120 -XX:MaxMetaspaceSize=512M'
        MappedPaths: '/f24-private/*'
        ECSClusterName: !Ref ECSClusterName
        Subnets: !Ref VpcEgressSubnetsIds
        VpcId: !Ref VpcId
        EcsDefaultSecurityGroup: !Ref EcsDefaultSecurityGroup
        LoadBalancerListenerArn: !Ref ApplicationLoadBalancerListenerArn
        LoadbalancerRulePriority: !Ref MicroserviceNumber
        TaskRoleManagedPolicyArn: !Ref DeliveryMicroserviceTaskManagedPolicy
        AlbSecurityGroup: !Ref AlbSecurityGroup
        EcsLogGroup: !Ref EcsLogGroup
        LogAlarmStrategyV1: !Ref LogAlarmStrategy

  # Grant operational rights to PN-F24 microservice
  F24MicroserviceTaskManagedPolicy:
    Type: AWS::IAM::ManagedPolicy
    Properties:
      PolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Action:
              - sqs:ChangeMessageVisibility
              - sqs:ChangeMessageVisibilityBatch
              - sqs:DeleteMessage
              - sqs:DeleteMessageBatch
              - sqs:GetQueueAttributes
              - sqs:GetQueueUrl
              - sqs:ReceiveMessage
              - sqs:SendMessage
              - sqs:SendMessageBatch
            Resource:
              - !Ref PnF24InternalQueueARN
              - !Ref SafeStorageToF24QueueARN
          - Effect: Allow
            Action:
              - dynamodb:GetItem
              - dynamodb:Query
              - dynamodb:PutItem
              - dynamodb:TransactWriteItems
              - dynamodb:ExecuteTransaction
            Resource:
              - !Sub "${F24MetadataSetTableArn}"
              - !Sub "${F24FileTableArn}"
          - Effect: Allow
            Action:
              - events:PutEvents
            Resource:
              - !Ref F24EventBusARN

  # Expose PN-f24 microservice public API with API-GW for B2B usage
  F24MicroservicePublicAPI:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub "${TemplateBucketBaseUrl}/fragments/api-gw-expose-service-openapi.yaml"
      Parameters:
        MicroServiceUniqueName: !Sub '${ProjectName}-f24'
        IntendedUsage: B2B
        DnsName: !Ref ApiDnsName
        ProjectName: !Ref ProjectName
        ServiceApiPath: 'f24'
        NetworkLoadBalancerLink: !Ref NetworkLoadBalancerLink
        ApplicationLoadBalancerDomain: !Ref ApplicationLoadBalancerDomain
        AlarmSNSTopicArn: !Ref AlarmSNSTopicArn
        CloudwatchLogKinesisStreamArn: !Ref LogsKinesisSourceStreamArn
        OpenApiBucketName: !Ref MicroserviceBucketName
        #TODO Come si chiama lo yaml nel bucket?
        OpenApiBucketKey: !Sub ${MicroserviceBucketBaseKey}/docs/openapi/aws/api-internal-f24.yaml


  # Dashboard
  F24MicroserviceCloudWatchDashboard:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub "${TemplateBucketBaseUrl}/fragments/microservice-cloudwatch-dashboard.yaml"
      Parameters:
        DashboardName: !Sub "${ProjectName}-f24"
        DynamoDBTableNames: !Join
          - ','
          - - !Ref F24MetadataSetTableName
          - - !Ref F24FileTableName
        RestApiStageArns: !Join
          - ','
          - - !GetAtt F24MicroservicePublicAPI.Outputs.RestApiStageArn
        RestApiNames: !Join
          - ','
          - - !GetAtt F24MicroservicePublicAPI.Outputs.RestApiName
        AlarmArns: !Join
          - ','
          - - !GetAtt F24Microservice.Outputs.FatalLogsMetricAlarmArn
            - !GetAtt F24MicroservicePublicAPI.Outputs.RestApiErrorAlarmArn
            - !GetAtt F24MicroservicePublicAPI.Outputs.RestApiLatencyAlarmArn
        QueueArns: !Join
          - ','
          - - !Ref PnF24InternalQueueARN
            - !Ref SafeStorageToF24QueueARN
            - !Ref F24EventBusDLQARN
        LogGroupsNames: !Join
          - ','
          - - !Sub '/aws/ecs/${ProjectName}-f24'

  # Event Bus to target bus role
  F24EventBusTargetRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Statement:
          - Action: sts:AssumeRole
            Effect: Allow
            Principal:
              Service: events.amazonaws.com
        Version: "2012-10-17"
      Policies:
        - PolicyName: putEventIntoTargetBus
          PolicyDocument:
            Statement:
              - Sid: putEvents
                Action:
                  - events:PutEvents
                Effect: Allow
                Resource:
                  - !Ref PnCoreTargetEventBus

  # Event Bus rule that direct event to target event bus
  F24EventBusToTarget:
    Type: AWS::Events::Rule
    Properties:
      Description: Route Address Manager Events to target event bus
      RoleArn: !GetAtt F24EventBusTargetRole.Arn
      EventBusName: !Ref F24EventBusName
      EventPattern:
        detail-type: [ "PnF24OutcomeEvent" ]
        source: [ "pn-f24" ]
      Targets:
        - Id: !Sub '${ProjectName}-F24Bus-PnCoreTargetEventBus'
          Arn: !Ref PnCoreTargetEventBus
          RoleArn: !GetAtt F24EventBusTargetRole.Arn
          DeadLetterConfig:
            Arn: !Ref F24EventBusDLQARN