AWSTemplateFormatVersion: '2010-09-09'
Description: Some storage with input and output

Parameters:
  ProjectName:
    Type: String
    Description: Nome dell'ambiente destinazione

  # Unused but required by CD pipeline
  MicroserviceNumber:
    Type: Number
    Description: An unique number that identify the microservice inside the ECS cluster.

  # Unused but required by CD pipeline
  TemplateBucketBaseUrl:
    Type: String
    Description: URL da cui caricare i frammenti di template di infrastruttura

  Version:
    Type: String
    Description: 'keep track of used projects commitIds'

  LogsKinesisSourceStreamArn:
    Type: String
    Description: 'Where to send Logs'

  AlarmSNSTopicName:
    Type: String
    Description: 'Topic alarm'

  LogRetention:
    Type: Number
    Default: 14

Resources:
  # Dynamo Table for F24MetadataSet
  F24MetadataSetTable:
    Type: AWS::DynamoDB::Table
    UpdateReplacePolicy: Retain
    DeletionPolicy: Retain
    Properties:
      TableName: !Sub '${ProjectName}-f24MetadataSet'
      AttributeDefinitions:
        - AttributeName: "pk"
          AttributeType: "S"
      KeySchema:
        - AttributeName: "pk"
          KeyType: "HASH"
      BillingMode: "PAY_PER_REQUEST"
      TimeToLiveSpecification:
        AttributeName: "ttl"
        Enabled: true
      PointInTimeRecoverySpecification:
        PointInTimeRecoveryEnabled: true

  # Dynamo Table for F24File
  F24FileTable:
    Type: AWS::DynamoDB::Table
    UpdateReplacePolicy: Retain
    DeletionPolicy: Retain        
    Properties:
      TableName: !Sub '${ProjectName}-f24File'
      AttributeDefinitions:
        - AttributeName: "pk"
          AttributeType: "S"
        - AttributeName: "fileKey"
          AttributeType: "S"
      KeySchema:
        - AttributeName: "pk"
          KeyType: "HASH"
      GlobalSecondaryIndexes:
        - IndexName: "fileKey-index"
          KeySchema:
            - AttributeName: fileKey
              KeyType: "HASH"
          Projection:
            ProjectionType: "ALL"
      BillingMode: "PAY_PER_REQUEST"
      TimeToLiveSpecification:
        AttributeName: "ttl"
        Enabled: true
      PointInTimeRecoverySpecification:
        PointInTimeRecoveryEnabled: true

  PnF24InternalQueue:
    Type: AWS::CloudFormation::Stack
    UpdateReplacePolicy: Retain
    DeletionPolicy: Retain    
    Properties:
      TemplateURL: !Sub "${TemplateBucketBaseUrl}/fragments/sqs-queue.yaml"
      Parameters:
        QueueName: !Sub '${ProjectName}-f24_internal'
        HasDLQ:  "true"
        AlarmSNSTopicName: !Ref AlarmSNSTopicName
        VisibilityTimeout: 60
        MaxReceiveCount: 10
        DelaySeconds: 1

  PnF24LogGroup:
    Type: AWS::CloudFormation::Stack
    UpdateReplacePolicy: Retain
    DeletionPolicy: Retain    
    Properties:
      TemplateURL: !Sub "${TemplateBucketBaseUrl}/fragments/log-group.yaml"
      Parameters:
        LogGroupName: !Sub '${ProjectName}-f24'
        LogsKinesisSourceStreamArn: !Ref LogsKinesisSourceStreamArn
        LogGroupRetention: !Ref LogRetention


Outputs:

  # Dynamo table
  F24MetadataSetTableName:
    Description: Name of dynamodb table containing f24 metadata set information's
    Value: !Ref F24MetadataSetTable
  F24MetadataSetTableArn:
    Description: ARN of dynamodb table containing f24 metadata set information's
    Value: !Sub '${F24MetadataSetTable.Arn}'
  F24FileTableName:
    Description: Name of dynamodb table containing f24 files information's
    Value: !Ref F24FileTable
  F24FileTableArn:
    Description: ARN of dynamodb table containing f24 files information's
    Value: !Sub '${F24FileTable.Arn}'

  # PnF24 Internal QUEUE
  PnF24InternalQueueName:
    Value: !GetAtt PnF24InternalQueue.Outputs.QueueName
    Description: internal queue name
  PnF24InternalQueueARN:
    Value: !GetAtt PnF24InternalQueue.Outputs.QueueARN
    Description: internal queue arn
  PnF24InternalDLQName:
    Value: !GetAtt PnF24InternalQueue.Outputs.DeadLetterQueueName
    Description: internal-DLQ queue name
  PnF24InternalDLQURL:
    Value: !GetAtt PnF24InternalQueue.Outputs.DeadLetterQueueURL
    Description: internal-DLQ queue url
  PnF24InternalDLQARN:
    Value: !GetAtt PnF24InternalQueue.Outputs.DeadLetterQueueARN
    Description: internal-DLQ queue ARN
  PnF24InternalDLQAlarmARN:
    Value: !GetAtt PnF24InternalQueue.Outputs.SqsDLQAlarmArn
    Description: internal-DLQ alarm ARN
  F24InternalAgeAlarmARN:
    Value: !GetAtt PnF24InternalQueue.Outputs.SqsAgeAlarmArn
    Description: internal-DLQ age alarm ARN

  # Log group exports
  EcsLogGroup:
    Value: !GetAtt   PnF24LogGroup.Outputs.LogGroupName