package it.pagopa.pn.f24.exception;

public class PnF24ExceptionCodes {

    public static final String ERROR_CODE_F24_PATH_TOKENS_NOT_ALLOWED = "PN_F24_PATH_TOKENS_NOT_ALLOWED";
    public static final String ERROR_CODE_VALIDATE = "PN_F24_VALIDATE";
    public static final String ERROR_CODE_F24_UPLOADFILEERROR = "PN_F24_UPLOADFILEERROR";
    public static final String ERROR_CODE_F24_METADATA_VALIDATION_DIFFERENT_SHA256 = "PN_F24_METADATA_VALIDATION_DIFFERENT_SHA256";
    public static final String ERROR_CODE_F24_METADATA_VALIDATION_MULTI_TYPE = "PN_F24_METADATA_VALIDATION_MULTI_TYPE";
    public static final String ERROR_CODE_F24_METADATA_VALIDATION_INCONSISTENT_APPLY_COST = "PN_F24_METADATA_VALIDATION_INCONSISTENT_APPLY_COST";
    public static final String ERROR_CODE_F24_ERRORCOMPUTECHECKSUM = "PN_F24_ERRORCOMPUTECHECKSUM";
    public static final String ERROR_CODE_F24_EVENTTYPENOTSUPPORTED = "PN_F24_EVENTTYPENOTSUPPORTED";
    public static final String ERROR_CODE_F24_HANDLEEVENTFAILED = "PN_F24_HANDLEEVENTFAILED";
    public static final String ERROR_MESSAGE_INVALID_METADATA = "Invalid metadata for payment with recipientIndex : %s attachmentIndex : %s";
    public static final String ERROR_CODE_F24_SAVE_METADATA_CONFLICT = "PN_F24_SAVEMETADATACONFLICT";
    public static final String ERROR_CODE_F24_METADATA_NOT_FOUND = "PN_F24_METADATANOTFOUND";
    public static final String ERROR_CODE_F24_READ_FILE_ERROR = "PN_F24_READ_FILE_ERROR";

}
